// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type DeleteRequest struct {
	UserId int64 `json:"user_id"`
}

type DeleteResponse struct {
	UserId int64 `json:"user_id"`
}

type ListRequest struct {
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
	SortType int32 `json:"sort_type"`
}

type ListResponse struct {
	Users      []UserInfoResponse `json:"users"`
	NextCursor int64              `json:"next_cursor"`
	IsEnd      bool               `json:"is_end"`
}

type LoginRequest struct {
	Mobile   string `json:"mobile:omitempty" `
	Email    string `json:"email:omitempty"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId int64 `json:"user_id"`
	Token  Token `json:"token"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	IsAdmin  bool   `json:"is_admin"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
}

type Token struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type UpdateRequest struct {
	UserId   int64  `json:"user_id"`
	Name     string `json:"name:omitempty"`
	Password string `json:"password:omitempty"`
	Email    string `json:"email:omitempty"`
	Mobile   string `json:"mobile:omitempty"`
	IsAdmin  bool   `json:"is_admin:omitempty"`
}

type UpdateResponse struct {
	UserId int64 `json:"user_id"`
}

type UserInfoRequest struct {
	UserId int64 `path:"user_id"`
}

type UserInfoResponse struct {
	UserId     int64  `json:"user_id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Mobile     string `json:"mobile"`
	IsAdmin    bool   `json:"is_admin"`
	IsDelete   bool   `json:"is_delete"`
	LastLogin  int64  `json:"last_login"`
	CreateTime int64  `json:"create_time"`
	UpdateTime int64  `json:"update_time"`
}
